### ISSUE TITLE
Adding attacker/defence Combatant with for loop

### ISSUE THREAD

**Issue by ozandem** [patrykstefanski/og-battle-engine#2]
Hi,

Firstly i loved your code and work. I try to implant your code to my project but I can not add attack/defence combatant with for loop. It comes with error of course (unexpected 'for' (T_FOR))

To be clear I explain what I try to do;
1) I create an array for every defence player with for loop `${"defenceplayer" . $i} = array("tech lv,ships amount etc")`
2) Then for every $defenceplayer$i I try create new Combatant like this: 
``` 
$defenders =
 [
for ($x=1; $x <$i ; $x++) { 
		new Combatant(
        ${"defenceplayer" . $x}[1],
        ${"defenceplayer" . $x}[2],
        ${"defenceplayer" . $x}[3],
        [
            OG::LIGHT_FIGHTER => ${"defenceplayer" . $x}[4],
                   .
                   .
                   .
        ],
    ),
	}
];
```
3) But I can not use for loop in $defender = []
4) I try to use before $defender = [] with new $defender = [] but it didnt work either.

Any advice would be welcome.

Thanks.

**Comment by patrykstefanski** [comment]
> It comes with error of course (unexpected 'for' (T_FOR))

PHP is trying to say that you cannot put a for loop inside of an array.

> 1. I create an array for every defence player with for loop `${"defenceplayer" . $i} = array("tech lv,ships amount etc")`

I am assuming you have something like this:
```php
for ($i = 0; $i < 2; $i++) {
  ${"defenceplayer" . $i} = array(10, 11, 12, 1000, 2000);
  //                              techs       LF    HF
}
```

Then, you probably can use something like this:
```php
$i = 2; // number of defenders
$defenders = array();
for ($x = 0; $x < $i; $x++) { // I changed the index from 1 to 0
  $defenders[$x] = new Combatant(
    ${"defenceplayer" . $x}[0], // weapons technology (note I changed the index from 1 to 0)
    ${"defenceplayer" . $x}[1], // shielding technology
    ${"defenceplayer" . $x}[2], // armor technology
    array(
      OG::LIGHT_FIGHTER => ${"defenceplayer" . $x}[3],
      OG::HEAVY_FIGHTER => ${"defenceplayer" . $x}[4],
      // ...
    )
  );
}
```

**Comment by ozandem** [comment]
Yes, your code is working well. Thank you for your answer.
